import {
  Aldrich,
  Baloo_Bhai_2,
  Geist,
  Geist_Mono,
  Titan_One,
} from "next/font/google"
import "./globals.css"
import ClientProvider from "@/libs/ClientProvider"
import { getSetting } from "@/libs/SettingService"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

const balooBhai = Baloo_Bhai_2({
  variable: "--font-baloo",
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
})

const titan = Titan_One({
  variable: "--font-titan",
  subsets: ["latin"],
  weight: "400",
})

const aldrich = Aldrich({
  variable: "--font-aldrich",
  subsets: ["latin"],
  weight: ["400"],
})

const setting = await getSetting()

export const metadata = {
  title: "Pengumuman Kelulusan | " + setting.nama_sekolah,
  description: "Generated by create next app",
  nama_sekolah: setting.nama_sekolah,
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${aldrich.variable} ${geistMono.variable} ${balooBhai.variable} ${titan.variable} antialiased`}
      >
        <ClientProvider>{children}</ClientProvider>
      </body>
    </html>
  )
}
